# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "LASCAR @ ESWC 2020"
description: "2nd Workshop on Large Scale RDF Analytics"
baseurl: ""
url: "http://lascar.sda.tech/"
permalink: "/blog/:title.html"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/call-for-papers.html", text: "Call for Papers"}
 - {permalink: "/blog/", text: "News"}
 - {permalink: "/submission/", text: "Submissions and Dates"}
 - {permalink: "/team/", text: "Committes"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "#", text: "Past Workshops"}
bottomNavigationLinks:
 - {link: "https://www.easychair.org/conferences/?conf=lascar20", text: "Submit your work"}
rightNavigationButtons:
 - {link: "https://www.easychair.org/conferences/?conf=lascar20", text: "Submit your work"}

# Hero Block
heroImage: "ESWC_2020_location.jpg"
heroTitle: "LASCAR <typeout> 2020"
eventDate: "May 31, 2020 - Jun 4, 2020 Heraklion, Crete, Greece"
typeoutTextValues: '"", "2nd Workshop on Large Scale RDF Analytics", "at ESWC"'
typeoutFallback: "at ESWC"
heroButtons:
 - {permalink: "/blog/call-for-papers.html", text: "Call for Papers"}
 - {link: "https://www.easychair.org/conferences/?conf=lascar20", text: "Submit your work"}

# About Block
aboutTitle: "About LASCAR Workshop"
aboutBlock:

 - {title: "About", text: "This workshop on Large Scale RDF Analytics (LASCAR) invites papers and posters related to the problems faced when dealing with the enormous growth of linked datasets, and by the advancement of semantic web technologies in the domain of large scale and distributed computing. We will particularly welcome research efforts exploring the use of generic big data frameworks like Apache Spark, Apache Flink, or specialized libraries like Giraph, Tinkerpop, SparkSQL etc. for Semantic Web technologies. The goal is to demonstrate the use of existing frameworks and libraries to exploit Knowledge Graph processing and to discuss the solutions to the challenges and issues arising therein. Moreover, we will organize a related talk by an expert speaker, and also arrange a panel discussion among experts and scientists working in the area of distributed semantic analytics. LASCAR targets a range of interesting research areas in large scale processing of Knowledge Graphs, like querying, inference, and analytics, therefore we expect a wider audience interested in attending the workshop." }
 - {title: "Topic of interest", text: "This workshop at the Extended Semantic Web Conference (ESWC) seeks original “articles and posters” describing theoretical and practical methods as well as techniques for performing scalable analytics on knowledge graphs. The topics relevant to this workshop include, but are not limited to distributed and scalable: <ul> <li>Decentralized KG data management including parsing, compression, partitioning and smart indexing</li> <li>Information retrieval using parallelization or optimization of querying and inference </li> <li>Large scale KG enrichment using link prediction, entity resolution, entity disambiguation or similarity estimation,</li> <li>Machine Learning e.g. clustering, blocking, or anomaly detection</li><li>Complex analytics with distributed KG embeddings </li> <li>Connecting property Graphs with RDF and reasoning </li> <li>Use-cases presenting semantic technologies at industry scale.</li></ul>" }
 - {text: "<a class='twitter-timeline' data-width='500' data-height='400' data-theme='light' href='https://twitter.com/lascarworkshop?ref_src=twsrc%5Etfw'>Tweets by LASCAR Workshop</a> <script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>" }


 # Submission Block
submissionTitle: "Submissions"
submissionBlock:

 - {title: "Submission Guidelines", text: "All papers should be formatted according to the standard <a href='http://www.springer.com/us/computer-science/lncs/conference-proceedings-guidelines'>LNCS Style</a>. All papers will be peer reviewed using the single-blind approach. Authors of the accepted papers will be asked to register for the workshop and will have the opportunity to present and participate in the workshop. Long papers should not be longer than 10 pages including the references, and short papers should not exceed 6 pages, including all references.  The accepted papers will be published online in CEUR Workshop Proceedings (<a href='http://CEUR-WS.org'>CEUR-WS.org</a>). Proceedings and available for download after the conference. The pre-print will be made available during the conference. The authors of the accepted posters will be invited to present their posters at the workshop.</p></br><h4>Please submit your work via <a href='https://www.easychair.org/conferences/?conf=lascar19'>EasyChair</a>.</h4>" }
 - {title: "Important Dates", text: "<ul> <li>Electronic submission of full papers: <strong>February 28th, 2020</strong></li> <li>Notification of paper acceptance: <strong>March 27th, 2020</strong></li> <li>Camera-ready of accepted papers: <strong>April 10th, 2020</strong></li> <li>Workshop day: May 31st, 2020</li></ul>" }

 # Latest News Block
latestNewsTitle: "Latest news"
cfpLink: /blog/call-for-papers.html
cfpText: "Read Call for Papers"

# Keynote Speakers Block
keynoteSpeakersImage: "keynote-speakers.jpg"
keynoteSpeakersCount: 4
keynoteSpeakersTitle: "Speakers"
keynoteSpeakersButtonText: "More details about the speakers"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "https://2020.eswc-conferences.org/wp-content/uploads/2017/12/6667_aea1b808a02d1584b38e956d345df570_2.jpg"
venueSmallImage1: "https://2020.eswc-conferences.org/wp-content/uploads/2017/12/13181_Knossos-Royal-Villas-6_1.jpg"
venueSmallImage2: "https://2020.eswc-conferences.org/wp-content/uploads/2017/12/Aldemar-Royal-Villas-5-12_0.jpg"
venueSmallImage3: "https://2020.eswc-conferences.org/wp-content/uploads/2017/12/aldemar_royal_village_12_0.jpg"
venueTitle: "<a href='https://2020.eswc-conferences.org/conference-venue/' target='_blank'><font color='FFFFFF'>Aldemar Knossos Royal & Royal Villa *****</font></a>"
venueFeatures: ["A large conference center containing two large halls", "The halls can host over 900 people", "Located right next to the sea"]

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Submit your contribution work"
subscribeAction: "https://www.easychair.org/conferences/?conf=lascar20"
subscribeInfo: "Submission will be open open until <strong>February 28th, 2020</strong> ."


# Footer
socialLinks:
 - {link: "https://twitter.com/SDA_Research", icon: "twitter"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "lascar"

# Speakers List Block
showSessions: true